<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46" started-at="2019-01-29T07:33:36Z" finished-at="2019-01-29T07:33:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46" started-at="2019-01-29T07:33:36Z" finished-at="2019-01-29T07:33:36Z">
      <class name="Test_Cases.Login_TC">
        <test-method status="PASS" signature="Initializesetup()[pri:0, instance:Test_Cases.Login_TC@6ea6d14e]" name="Initializesetup" is-config="true" duration-ms="9" started-at="2019-01-29T13:03:36Z" finished-at="2019-01-29T13:03:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initializesetup -->
        <test-method status="FAIL" signature="f()[pri:0, instance:Test_Cases.Login_TC@6ea6d14e]" name="f" duration-ms="17" started-at="2019-01-29T13:03:36Z" finished-at="2019-01-29T13:03:36Z">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[org/apache/xmlbeans/XmlObject]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: org/apache/xmlbeans/XmlObject
	at Utilities.XcelReader.getExcelValue(XcelReader.java:24)
	at Functional_Library.Common_Methods.getExcelValue(Common_Methods.java:69)
	at Test_Cases.Login_TC.getInputValue(Login_TC.java:27)
	at Test_Cases.Login_TC.f(Login_TC.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: java.lang.ClassNotFoundException: org.apache.xmlbeans.XmlObject
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- Test_Cases.Login_TC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
